### ISSUE TITLE
Initial deployment via pipelines fails

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/deploynaut#103]
The problem is that a deployment always does a DB backup snapshot in case it needs to restore. If a site is being deployed for the first time, there is nothing to backup.

https://github.com/silverstripe/deploynaut/blob/master/code/model/steps/DeploymentPipelineStep.php#L110

A simple fix would be to skip snapshots if there is no "currently deployed" sha on the target environment.

**Comment by stojg** [comment]
This is closed by 8884c69476fd67d71ba9e107773f5909ca572b34
