### ISSUE TITLE
Performance issue with Snapshots list

### ISSUE THREAD

**Issue by IgorNadj** [silverstripe/deploynaut#108]
Hi yalls,

My project has 12 pages of snapshots (one is created at each deployment automatically by pipelines), and the page takes a good minute to load.

Most likely an issue with not lazy loading the data from the database in the pagination.
Thanks,
Igor

**Comment by stojg** [comment]
In memory cache implemented by 73f4f840f721ce788b632d194d5d0ad5a8b17aad should have improved the performance

**Comment by chillu** [comment]
Yay!!
