### ISSUE TITLE
Let users change their password without CMS access

### ISSUE THREAD

**Issue by ss23** [silverstripe/deploynaut#89]

**Comment by stojg** [comment]
@ss23 @sminnee Can we close this ticket?I believe that it's not part of the deploynaut module at all.

**Comment by ss23** [comment]
@stojg See above discussion with @tractorcow regarding whether it should be part of deploynaut. That being said, I think I saw something about how deploynaut requires CMS now. If that's the case, then I think that solves the issue.

**Comment by stojg** [comment]
nope, but we have a "base" project (that requires deploynaut) that now requires CMS adding user functionality, so it's not included in this module.

**Comment by ss23** [comment]
Sounds fixed enough to me then!

**Comment by stojg** [comment]
excellent
